apiVersion: v1
kind: Service
metadata:
  name: iseek-server-service
spec:
  selector:
    app: iseek-server
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iseek-server
spec:
  selector:
    matchLabels:
      app: iseek-server
  replicas: 2
  template:
    metadata:
      labels:
        app: iseek-server
    spec:
      containers:
      - name: iseek-server
        image: iseek-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000